# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
ENABLE: JSON, YAML # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
ENABLE_LINTERS:  # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - JAVASCRIPT_ES
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_PRETTIER
  - JSX_ELINT
  - MAKEFILE_CHECKMAKE
  - POWERSHELL_POWERSHELL
  - POWERSHELL_POWERSHELL_FORMATTER
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
POST_COMMANDS:
  - command: npm run build
FILTER_REGEX_EXCLUDE: (/src)